### ISSUE TITLE
Multiline support for vertical RadioGroup? 

### ISSUE THREAD

**Issue by noman200898** [TercyoStorck/group_radio_button#10]
How we will handle if vertical RadioGroup has long text? Recent I have face this issue, Please see the attachment : 

![flutter_01](https://user-images.githubusercontent.com/38140300/154417533-1d4d32dc-4a8a-44ae-a403-4c6d45f32c13.png)

**Comment by TercyoStorck** [comment]
Can you post the entire view code?

**Comment by noman200898** [comment]
> Can you post the entire view code?

Sorry for the late, here is the code I want to use:

`
 static const List<String> kycLevel = [
    'Level-1 (Phone, email, bank)',
    'Level-2 (Phone, email, bank, national id, driving licence)',
    "Level-3 (Phone, email, bank, national id, driving licence, passport)",
    "Level-4 (Phone, email, bank, national id, driving licence, passport, google_2fa, company)"
  ];
  
Widget radioGroup(List<String> list, String selected, Function(String index) onSelect) {
  return SizedBox(
    width: Get.width,
    child: RadioGroup<String>.builder(
      direction: Axis.vertical,
      activeColor: Get.theme.primaryColor,
      groupValue: selected,
      horizontalAlignment: MainAxisAlignment.center,
      onChanged: (value) => {onSelect(value ?? "")},
      items: list,
      itemBuilder: (item) => RadioButtonBuilder(item),
    ),
  );
`

**Comment by TercyoStorck** [comment]
Sorry for the late @_@

I've solved it and will publish the fix soon. Thank you for report it.
