### ISSUE TITLE
Adjust padding

### ISSUE THREAD

**Issue by fasadin** [TercyoStorck/group_radio_button#11]
Item has (left) padding where there is no possibility to override this
On examples given in this repo it's clear to see that there is padding added by default.

I think this is nice package which I am using, but default padding makes difficult to design app they way I want 
![image](https://user-images.githubusercontent.com/5629134/205450081-5fd1451b-848c-426d-8298-255ad93c2e3e.png)

**Comment by TercyoStorck** [comment]
Hi.

This padding is from Radio widget from flutter. I'm not allowed to remove it. Sorry =/

If you find a way, please. Make a fork and do a Pull Request with the solution =)
