### ISSUE TITLE
Change style of radio

### ISSUE THREAD

**Issue by fasadin** [TercyoStorck/group_radio_button#12]
Would be nice to give radio your own style. I would like to achieve something as follows 
![image](https://user-images.githubusercontent.com/5629134/205450212-d73c791b-8ed4-4c78-8aa4-587127f1fad5.png)
so:
- change border color
- change background color

**Comment by TercyoStorck** [comment]
Hi.

You can change `activeColor` and I'll add a new propierty called `fillColor` that'll do what you want.
