### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by nipunasudha** [TercyoStorck/group_radio_button#5]
Null safety in Flutter 2.0 please?

**Comment by TercyoStorck** [comment]
Hi,

I'll do it as soon as possible. But for now I'm very busy.

**Comment by nipunasudha** [comment]
No worries, thank you very much for your time!

**Comment by nipunasudha** [comment]
Is there any news on this one?

**Comment by rithik-dev** [comment]
I have created a pull request for the same! #6

**Comment by TercyoStorck** [comment]
Updated!
