### ISSUE TITLE
Screen Shot

### ISSUE THREAD

**Issue by pishguy** [TercyoStorck/group_radio_button#8]
is there any screen shot?

**Comment by TercyoStorck** [comment]
https://raw.githubusercontent.com/TercyoStorck/group_radio_button/master/assets/1.jpg

https://raw.githubusercontent.com/TercyoStorck/group_radio_button/master/assets/2.jpg

https://raw.githubusercontent.com/TercyoStorck/group_radio_button/master/assets/3.jpg
